### PR TITLE
[OPTIMIZE] SVG icon

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by featdd** [comment]
Hi @xerc,

I'm missing a description for what this changes are necessary for?
Why did you delete the ext_icon.svg?

Greetings
Daniel

**Comment by xerc** [comment]
i cleaned and optimized your icon because i want to contrubute at least a bit
and the `/ext_` is not needet at this location anymore (including duplication)

**Comment by featdd** [comment]
Hi @xerc,

this is solved here: ff10dc129435cf4e8bc9c7cd4da96252cd1522a3

Greetings
Daniel

**Comment by xerc** [comment]
@featdd you may still include my optimz. version

**Pull request closed without merging**
